### ISSUE TITLE
Information request: How long should this take?

### ISSUE THREAD

**Issue by Lewiscowles1986** [trussworks/terraform-aws-ses-domain#12]
So I'm testing this out for a new greenfield project and

```
module.ses_domain.aws_ses_domain_identity_verification.main[0]: Still creating... [30m31s elapsed]
module.ses_domain.aws_ses_domain_identity_verification.main[0]: Still creating... [30m41s elapsed]
module.ses_domain.aws_ses_domain_identity_verification.main[0]: Still creating... [30m51s elapsed]
module.ses_domain.aws_ses_domain_identity_verification.main[0]: Still creating... [31m1s elapsed]
```

Is this indicative of the time to setup?

It's definitely taken the most time inside this which I'm using as a module as the docs indicate. Perhaps it needs hints?

**Comment by dynamike** [comment]
If SES can't validate the domain because it's private or something, it will timeout. Were you able to resolve this?

**Comment by Lewiscowles1986** [comment]
Yes. Apologies for not closing sooner, it was in my backlog of actions to take. If anyone should encounter this error, it for me was because I had not undertaken the action to change the nameservers to AWS from a domain someone else had purchased, and yet another person had transferred to amazon. This took < 5 minutes to complete once that was done and the DNS had fully propagated.

### Two lessons

1. Buy domains at Amazon, or at-least ensure nameservers are setup correctly before running any terraform DNS (oddly enough some other terraform was working).
2. I believe if I'd have read the docs on , then I'd have realized setting `enable_verification` to `false` would have bypassed any issues and it may have worked anyway. https://github.com/terraform-providers/terraform-provider-aws/issues/7562 points to this being operator error. I may follow up with a shorter default for this step if you are amenable
