### ISSUE TITLE
SPF for primary domain

### ISSUE THREAD

**Issue by lleger** [trussworks/terraform-aws-ses-domain#120]
Hi!

This module creates two SPF records, one for the mail from domain and one for the apex (root) domain. I know there's an option to turn this off, but it turns _both_ off, so you still have to manually manage at least the mail from domain.

But my question is: why is this module making SPF records for the apex domain? As far as I can tell, this isn't required by SES. See below for the record set from the console:
![CleanShot 2022-05-13 at 14 17 55@2x](https://user-images.githubusercontent.com/52359/168375030-9d6c21dc-3b4e-4867-a653-eb4df37db233.png)

**Comment by esacteksab** [comment]
Looking at the [docs](https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-spf.html) it makes no mention of an SPF record for the apex or root domain. But looking [further](https://docs.aws.amazon.com/ses/latest/dg/mail-from.html) it does mention creating _both_ an `MX` record along with a `TXT` record for the SPF record. This is further supported by Terraform's [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_mail_from)

**Comment by lleger** [comment]
Thank you that is a perfect fix.
