### ISSUE TITLE
Issues downloading module via Terraform

### ISSUE THREAD

**Issue by isopy** [trussworks/terraform-aws-ses-domain#18]
We've successfully leveraged this module in the past, however we are currently seeing the following Terraform error when trying to pull down the module from your repo:

```
Initializing modules...
Downloading trussworks/ses-domain/aws 2.0.1 for ses_domain...
Error: Failed to download module
Could not download module "ses_domain" (ses.tf:1) source code from
"https://api.github.com/repos/trussworks/terraform-aws-ses-domain/tarball/v2.0.1//*?archive=tar.gz":
Error opening a gzip reader for
/var/folders/j9/hrt63y5j6cv175jm4zsr500r0000gp/T/getter676221457/archive: EOF.
```

Nothing has changed in our config code but here is the relevant code:

```
module "ses_domain" {
  source             = "trussworks/ses-domain/aws"
  version            = "1.0.2"
  domain_name        = "${var.domain_name}"
  mail_from_domain   = "mail.${var.domain_name}"
  route53_zone_id    = "${data.terraform_remote_state.vpc.outputs.public_zone_id}"
  from_addresses     = ["${var.aws_iam_user}@${var.domain_name}"]
  dmarc_rua          = "${var.aws_iam_user}@${var.domain_name}"
  receive_s3_bucket  = "${aws_s3_bucket.ses.id}"
  receive_s3_prefix  = "${var.receive_s3_prefix}"
  ses_rule_set       = "${aws_ses_receipt_rule_set.default-rule-set.id}"
}
```
I get the failure no matter which version I use. Let me know if I can provide any additional information.

```
~ terraform --version
Terraform v0.12.12
```

**Comment by esacteksab** [comment]
The Terraform Registry is currently experiencing an incident https://status.hashicorp.com/incidents/cgrw595c8kxc

This is fixed in Terraform 0.12.19 https://github.com/hashicorp/terraform/releases/tag/v0.12.19 which seems to have been caused by a library that Terraform used https://github.com/hashicorp/go-getter/pull/227

**Comment by isopy** [comment]
@esacteksab Thanks so much for the quick response and pointing out that status page that I wasn't aware of before.T he upgrade to 0.12.19 fixed it for us. Sorry for the noise.

**Comment by esacteksab** [comment]
No noise at all. It's been a pain point for us as well.
